name: Deploy static web app
on:
  push:
    branches:
      - main # Triggers the action on push to the 'main' branch
    # tags:
    #   - v*.*.* # Triggers the action on tag

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Specify your Node.js version
      
      # Step 3: Get tag version
      - name: Get tag version
        id: get_tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 4: Load environment variables from file (.env)
      - name: Set environment variables from Dotenv
        uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: .env

      # Step 5: Load environment variables from GitHub Secrets
      - name: Set environment variables from GitHub Secrets
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> $GITHUB_ENV

      # Step 6: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 7: Run build script
      - name: Build
        run: npm run build # Assumes there's a build script in package.json

      # Step 8: Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist