name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace secrets in script.js
        run: |
          sed -i "s|API_URL|${{ secrets.API_URL }}|g" script.js
          sed -i "s|API_KEY|${{ secrets.API_KEY }}|g" script.js
          sed -i "s|APP_KEY|${{ secrets.APP_KEY }}|g" script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
