name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      - name: Inject Secrets
        run: |
          mkdir -p public
          cat <<EOF > public/config.js
          window.API_URL='${{ secrets.API_URL }}';
          window.API_KEY='${{ secrets.API_KEY }}';
          window.APP_KEY='${{ secrets.APP_KEY }}';
          EOF

          export API_URL=${{ secrets.API_URL }}
          export API_KEY=${{ secrets.API_KEY }}
          export APP_KEY=${{ secrets.APP_KEY }}

      - name: Build
        run: |
          mkdir -p public
          cp index.html style.css script.js public/
          cp public/config.js public/
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
